### ISSUE TITLE
关于mpush_android_demo，启动崩溃问题

### ISSUE THREAD

**Issue by songyunbiao** [aliyun/alicloud-android-demo#189]
03-30 13:35:20.608 31833-31833/cloud.aliyun.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: cloud.aliyun.test, PID: 31833
                                                                   java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alibaba/sdk/android/utils/AlicloudTrackerManager;
                                                                       at com.alibaba.sdk.android.push.c.a.<init>(Unknown Source)
                                                                       at com.alibaba.sdk.android.push.c.a.a(Unknown Source)
                                                                       at com.alibaba.sdk.android.push.impl.j.a(Unknown Source)
                                                                       at com.alibaba.sdk.android.push.noonesdk.PushServiceFactory.init(Unknown Source)
                                                                       at com.alibaba.cloudpushdemo.application.MainApplication.initCloudChannel(MainApplication.java:35)
                                                                       at com.alibaba.cloudpushdemo.application.MainApplication.onCreate(MainApplication.java:25)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6013)
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:211)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1766)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6918)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alibaba.sdk.android.utils.AlicloudTrackerManager" on path: DexPathList[[zip file "/data/app/cloud.aliyun.test-1/base.apk"],nativeLibraryDirectories=[/data/app/cloud.aliyun.test-1/lib/arm, /vendor/lib, /system/lib]]
                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                       at com.alibaba.sdk.android.push.c.a.<init>(Unknown Source) 
                                                                       at com.alibaba.sdk.android.push.c.a.a(Unknown Source) 
                                                                       at com.alibaba.sdk.android.push.impl.j.a(Unknown Source) 
                                                                       at com.alibaba.sdk.android.push.noonesdk.PushServiceFactory.init(Unknown Source) 
                                                                       at com.alibaba.cloudpushdemo.application.MainApplication.initCloudChannel(MainApplication.java:35) 
                                                                       at com.alibaba.cloudpushdemo.application.MainApplication.onCreate(MainApplication.java:25) 
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035) 
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6013) 
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:211) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1766) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:145) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6918) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
                                                                   	Suppressed: java.lang.ClassNotFoundException: com.alibaba.sdk.android.utils.AlicloudTrackerManager
                                                                       at java.lang.Class.classForName(Native Method)
                                                                       at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                       at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                       		... 18 more
                                                                    Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by 164738777** [comment]
和楼主遇到同一个问题....

**Comment by asialee** [comment]
您好，之前因为demo的配置出错导致版本没有对上所以出现这个问题，现在已经修复了，重新pull下即可

**Comment by coolsili** [comment]
> 和楼主遇到同一个问题....

您好，这个bug又复现了
09-24 00:11:59.956 13742-13742/com.zkyx.onemachine E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zkyx.onemachine, PID: 13742
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/alibaba/sdk/android/utils/AlicloudTrackerManager;
        at com.alibaba.sdk.android.push.c.a.<init>(Unknown Source)
        at com.alibaba.sdk.android.push.c.a.a(Unknown Source)
        at com.alibaba.sdk.android.push.impl.j.a(Unknown Source)
        at com.alibaba.sdk.android.push.noonesdk.PushServiceFactory.init(Unknown Source)
        at com.zkyx.onemachine.AppApplication.initAliyunPush(AppApplication.java:129)
        at com.zkyx.onemachine.AppApplication.onCreate(AppApplication.java:94)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
        at android.app.ActivityThread.access$1500(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alibaba.sdk.android.utils.AlicloudTrackerManager" on path: DexPathList[[zip file "/data/app/com.zkyx.onemachine-2/base.apk"],nativeLibraryDirectories=[/data/app/com.zkyx.onemachine-2/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.alibaba.sdk.android.push.c.a.<init>(Unknown Source) 
        at com.alibaba.sdk.android.push.c.a.a(Unknown Source) 
        at com.alibaba.sdk.android.push.impl.j.a(Unknown Source) 
        at com.alibaba.sdk.android.push.noonesdk.PushServiceFactory.init(Unknown Source) 
        at com.zkyx.onemachine.AppApplication.initAliyunPush(AppApplication.java:129) 
        at com.zkyx.onemachine.AppApplication.onCreate(AppApplication.java:94) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697) 
    	Suppressed: java.lang.ClassNotFoundException: com.alibaba.sdk.android.utils.AlicloudTrackerManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
