### ISSUE TITLE
加载补丁成功后，应用持续崩溃

### ISSUE THREAD

**Issue by yangy996** [aliyun/alicloud-android-demo#190]
04-17 17:19:27.625 17827-17827/com.exam.app D/SophixStubApplication: 补丁加载成功！
04-17 17:19:27.627 17827-17827/com.exam.app E/Sophix.PatchManager:  replaceRealApplication
                                                                   java.lang.ClassNotFoundException
                                                                       at com.taobao.sophix.b.a.a.a.findClass(Sophix:199)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                       at com.taobao.sophix.a.c.n(Sophix:637)
                                                                       at com.taobao.sophix.a.c.a(Sophix:131)
                                                                       at com.taobao.sophix.a.e.initialize(Sophix:71)
                                                                       at com.exam.app.SophixStubApplication.attachBaseContext(SophixStubApplication.java:61)
                                                                       at android.app.Application.attach(Application.java:194)
                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:1009)
                                                                       at android.app.Instrumentation.newApplication(Instrumentation.java:993)
                                                                       at android.app.LoadedApk.makeApplication(LoadedApk.java:802)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5485)
                                                                       at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1602)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:163)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6343)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by xylitolhub** [comment]
@YY007H 是不是使用了加固或者SophixEntry没有Keep住？
