### ISSUE TITLE
使用热修复Sophix，加载补丁后导致应用崩溃。kotlin，协程出现找不到

### ISSUE THREAD

**Issue by diswy** [aliyun/alicloud-android-demo#203]
按文档集成了Sophix，在不使用kotlin协程的情况，加载补丁后都是可以正常运行，实现热修复。
问题在于，使用了kotlin的协程之后，则会出现如下日志：

java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.missing(MainDispatchers.kt:73)
        at kotlinx.coroutines.internal.MissingMainCoroutineDispatcher.isDispatchNeeded(MainDispatchers.kt:54)
        at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:373)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:160)
        at kotlinx.coroutines.channels.ActorKt.actor(Actor.kt:121)
        at kotlinx.coroutines.channels.ActorKt.actor$default(Actor.kt:112)....

提示Module with the Main dispatcher is missing该错误，问题可以复现，希望工程师可以解决一下该问题。kotlin版本 1.3.20，协程版本1.1.1

**Comment by SducodeMonkey** [comment]
热修复相关问题，可以添加钉钉群：21710469，有技术支持同学实时响应。

**Comment by dudukee** [comment]
近一年半过去了，还是没有支持。

![image](https://user-images.githubusercontent.com/3353717/91803646-abffc080-ec5d-11ea-9a76-deb16e5afe20.png)

![image](https://i.loli.net/2020/09/01/2ZvnS5sjdeglaIG.png)
