### ISSUE TITLE
在华为机型上初始化initCloudChannel（）报错

### ISSUE THREAD

**Issue by ZhangH2545** [aliyun/alicloud-android-demo#213]
Process: com.inthub.wuliubaodriver, PID: 8101
                  java.lang.NoClassDefFoundError: com.alibaba.sdk.android.utils.AlicloudTrackerManager
                      at com.alibaba.sdk.android.push.c.a.<init>(Unknown Source)
                      at com.alibaba.sdk.android.push.c.a.a(Unknown Source)
                      at com.alibaba.sdk.android.push.impl.j.a(Unknown Source)
                      at com.alibaba.sdk.android.push.noonesdk.PushServiceFactory.init(Unknown Source)
                      at com.inthub.wuliubaodriver.common.MyApplication.initCloudChannel(MyApplication.java:365)
                      at com.inthub.wuliubaodriver.common.MyApplication.onCreate(MyApplication.java:112)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
                      at android.app.ActivityThread.access$1800(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                      at android.os.Handler.dispatchMessage(Handler.java)
                      at android.os.Looper.loop(Looper.java)
                      at android.app.ActivityThread.main(ActivityThread.java)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by ZhangH2545** [comment]
玛雅，初始化都不行怎么用的？

**Comment by new-xd** [comment]
看错误是缺少一些依赖，请参考maven接入的方式接入看看
