### ISSUE TITLE
SSL handshake aborted: ssl=0xe0f47008: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by MyWdq** [aliyun/alicloud-android-demo#234]
android版本：9.0 

2020-07-27 09:35:20.076 17562-17723/com.jaygoo.demo W/System.err: java.io.IOException: createSocket exception: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xe0f47008: I/O error during system call, Connection reset by peer
2020-07-27 09:35:20.076 17562-17723/com.jaygoo.demo W/System.err:     at com.alibaba.mtl.log.d.x.createSocket(UtSslSocketFactory.java:108)
2020-07-27 09:35:20.076 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:181)
2020-07-27 09:35:20.076 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:299)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:472)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:26)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.alibaba.mtl.log.d.e.a(HttpUtils.java:212)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.alibaba.mtl.log.upload.a.a(UploadTask.java:220)
2020-07-27 09:35:20.077 17562-17723/com.jaygoo.demo W/System.err:     at com.alibaba.mtl.log.upload.a.I(UploadTask.java:142)
2020-07-27 09:35:20.078 17562-17723/com.jaygoo.demo W/System.err:     at com.alibaba.mtl.log.upload.a.run(UploadTask.java:51)
2020-07-27 09:35:20.078 17562-17723/com.jaygoo.demo W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
2020-07-27 09:35:20.078 17562-17723/com.jaygoo.demo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-07-27 09:35:20.078 17562-17723/com.jaygoo.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-07-27 09:35:20.078 17562-17723/com.jaygoo.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-07-27 09:35:20.078 17562-17723/com.jaygoo.demo W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by MyWdq** [comment]
移动数据分析出现这种异常~~~

**Comment by jiahui1988** [comment]
hello,请问这个问题解决了吗？我也想知道是怎么解决的
