### ISSUE TITLE
Android 崩溃分析不管用

### ISSUE THREAD

**Issue by John-tp** [aliyun/alicloud-android-demo#235]
错误日志如下：
2020-09-02 14:24:42.248 27000-27016/com.fengyuncx.tp.ali_plugin.demo E/MotuCrashSDK: do scan traces file
    java.io.FileNotFoundException: /data/anr/traces.txt (Permission denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at com.alibaba.motu.crashreporter.a$a$a.q(CatcherManager.java:869)
        at com.alibaba.motu.crashreporter.a$a$1.run(CatcherManager.java:945)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2020-09-02 14:24:42.288 27000-27000/com.fengyuncx.tp.ali_plugin.demo E/Telescope: [PLUGIN_MANAGER] The plugin [FdOverflowPlugin] is not supported!
2020-09-02 14:24:42.288 27000-27000/com.fengyuncx.tp.ali_plugin.demo E/Telescope: [PLUGIN_MANAGER] The plugin [MainThreadBlockPlugin] is not supported!
2020-09-02 14:24:42.296 27000-27000/com.fengyuncx.tp.ali_plugin.demo E/Telescope: [PLUGIN_MANAGER] The plugin [MemBitmapPlugin] is not supported!
2020-09-02 14:24:42.311 27000-27026/com.fengyuncx.tp.ali_plugin.demo E/Telescope: CALL CHECK......
2020-09-02 14:24:42.312 27000-27025/com.fengyuncx.tp.ali_plugin.demo E/Telescope: [ReportManager] You should pick a right concrete Bean interface, type: 0x1
2020-09-02 14:24:42.319 27000-27026/com.fengyuncx.tp.ali_plugin.demo E/Telescope: method check failed ....
2020-09-02 14:24:42.320 27000-27026/com.fengyuncx.tp.ali_plugin.demo E/Telescope: method check failed ....
2020-09-02 14:24:42.321 27000-27026/com.fengyuncx.tp.ali_plugin.demo E/Telescope: method check failed ....
2020-09-02 14:24:42.324 27000-27026/com.fengyuncx.tp.ali_plugin.demo E/Telescope: method check failed ....
2020-09-02 14:24:42.326 27000-27026/com.fengyuncx.tp.ali_plugin.demo E/Telescope: method check failed ....
2020-09-02 14:24:42.327 27000-27026/com.fengyuncx.tp.ali_plugin.demo E/Telescope: method check failed ....
2020-09-02 14:24:42.328 27000-27026/com.fengyuncx.tp.ali_plugin.demo E/Telescope: method check failed ....
2020-09-02 14:24:42.778 27000-27025/com.fengyuncx.tp.ali_plugin.demo E/Telescope: [ReportManager] You should pick a right concrete Bean interface, type: 0x3
2020-09-02 14:24:52.227 27000-27000/com.fengyuncx.tp.ali_plugin.demo E/SmoothPlugin: startSmCalculate
2020-09-02 14:24:52.236 27000-27000/com.fengyuncx.tp.ali_plugin.demo E/SmoothPlugin: stopSmoothSmCalculate
2020-09-02 14:24:52.410 27000-27000/com.fengyuncx.tp.ali_plugin.demo E/MethodChannel#ali_crash_report: Failed to handle method call

**Comment by John-tp** [comment]
flutter 调用android平台方法时如果在主线程,崩溃错误会被flutter捕获，程序不崩溃
