### ISSUE TITLE
适配Android Q的时候 推送报错 导致接收不到推送

### ISSUE THREAD

**Issue by BoBoJiangs** [aliyun/alicloud-android-demo#236]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.alibaba.sdk.android.push.notification.BasicCustomPushNotification.isBuildWhenAppInForeground()' on a null object reference
        at com.alibaba.sdk.android.push.notification.d.a(Unknown Source:32)
        at com.alibaba.sdk.android.push.MessageReceiver.showNotificationNow(Unknown Source:0)
        at com.aliyun.ams.emas.push.a.a(Taobao:104)
        at com.aliyun.ams.emas.push.AgooMessageReceiver.onReceive(Taobao:44)
        at com.alibaba.sdk.android.push.MessageReceiver.onReceive(Unknown Source:0)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3849)
        at android.app.ActivityThread.access$1500(ActivityThread.java:227)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1901)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by new-xd** [comment]
请升级到 移动推送 3.2.2 版本
